### ISSUE TITLE
Setting ArcGIS geometry to incorrect spatial reference

### ISSUE THREAD

**Issue by alaframboise** [Esri/terraformer-arcgis-parser#26]
The parser ignores the crs passed in for GeoJSON.  The following code results in the geometry.spatialReference.wkid set to 4326, whereas it should be 2913.

Please add a check for the crs wkid and apply that to the geometry's spatial reference wkid. 

```
  function terraformerConversion(geojson) {
            var json,
                arcgis;

            // Convert the geojson object to a Primitive json representation
            json = new Terraformer.Primitive(geojson);
            console.log(json.crs.properties.name);  // "urn:ogc:def:crs:EPSG::2913"

            // Convert to ArcGIS JSON
            arcgis = Terraformer.ArcGIS.convert(json);  
            console.log(arcgis[0].geometry.spatialRefernce.wkid); // 4326

            return arcgis;
        }
```

**Comment by jbtibor** [comment]
The error is because crs is compared to Terraformer.MercatorCRS using === what returns true only if both variables point to the same object instance:
around line 303: else if (geojson && geojson.crs === Terraformer.MercatorCRS)

Instead of === the properties of crs should be compared to the properties of Terraformer.MercatorCRS.
I.e. Terraformer.MercatorCRS could have an equals method.
